// Copies committed CSVs into public/ so Vite serves them as static assets.
// Runs before every build via the prebuild script in package.json.
//
// data/ stays the single source of truth. Copying rather than symlinking
// keeps the build working on Cloudflare, which checks the repo out fresh.

import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const destDir = resolve(root, 'public')
mkdirSync(destDir, { recursive: true })

// public/_headers is committed source, not generated data. It sets the
// cache rules that stop a stale index.html from loading an old JS bundle,
// so a build that dropped it would reintroduce exactly the caching problem
// it exists to prevent.
// The social card is generated by analysis/make_og_image.py into assets/,
// which is tracked, and copied here like the data files. A build without
// it still works; shared links just unfurl without an image, which is
// worth a warning rather than a failed build.
const ogSrc = resolve(root, 'assets/og.png')
const ogDest = resolve(destDir, 'og.png')
if (existsSync(ogSrc)) {
  copyFileSync(ogSrc, ogDest)
  console.log('copy-data: og.png copied')
} else {
  console.warn('copy-data: WARNING assets/og.png missing; shared links will '
    + 'unfurl without an image. Run analysis/make_og_image.py')
}

const headers = resolve(destDir, '_headers')
if (!existsSync(headers)) {
  console.warn('copy-data: WARNING public/_headers missing; cache headers '
    + 'will not be applied and stale pages may be served')
}

// [source file, header to write if it is missing]
const FILES = [
  ['data/snapshots.csv',
   'fetched_at,snapshot_date,race_id,cycle,venue,yes_side,prob,days_out,raw_price,inverted,volume,liquidity,spread,note'],
  ['data/poll_probabilities.csv',
   'computed_at,race_id,as_of_date,days_out,margin,prob,sigma,sigma_systematic,sigma_sampling,n_polls,effective_n,n_partisan,partisan_lean,excluded_partisan,sigma_final_assumed'],
  ['data/race_meta.json', '{}'],
  ['data/poll_history.csv',
   'race_id,as_of_date,days_out,margin,prob,sigma,n_polls,effective_n,n_partisan'],
]

for (const [rel, header] of FILES) {
  const src = resolve(root, rel)
  const dest = resolve(destDir, rel.split('/').pop())
  if (existsSync(src)) {
    copyFileSync(src, dest)
    console.log(`copy-data: ${rel} copied`)
  } else {
    // Never fail the build over missing data. A header-only file lets the
    // frontend render its empty state instead of erroring.
    writeFileSync(dest, header + '\n')
    console.log(`copy-data: ${rel} missing, wrote header only`)
  }
}
