// CSV parsing and shaping. Separate from the components so it can be
// reasoned about, and tested, without rendering anything.

// Volume below this is flagged as thin. Polymarket state races often sit in
// the low six figures, which one trader can move. A display flag, not a
// filter: the row still shows, it just carries a warning.
export const THIN_VOLUME = 250000

// A poll average worth less than this many equally-weighted polls is flagged.
// Several races currently sit at 1.0, meaning a single survey.
export const THIN_EFFECTIVE_N = 3

// Labels and candidate names come from data/race_meta.json, generated by
// analysis/race_meta.py from the same config the poll collector uses. Kept
// out of here so a nominee change happens in exactly one place.
export const FALLBACK_META = {
  label: null, dem: null, rep: null, dem_short: null, rep_short: null,
  kind: 'senate',
}

export function parseCsv(text) {
  // Split on any line ending. Python's csv module writes \r\n by default,
  // while files edited through a web UI use \n, so a single file can hold
  // both. Splitting on \n alone leaves a trailing \r on the last field of
  // every Python-written row, which lands in `note` and makes the row look
  // like a failed fetch.
  const lines = text.trim().split(/\r\n|\n|\r/).filter((l) => l.length)
  if (lines.length < 2) return []
  const headers = lines[0].split(',').map((h) => h.trim())
  return lines.slice(1).map((line) => {
    const cells = splitRow(line, headers.length)
    const row = {}
    headers.forEach((h, i) => { row[h] = (cells[i] ?? '').trim() })
    return row
  })
}

// Split into exactly n fields, letting the last column absorb extra commas.
// Keeps a comma inside an error message from shifting every column left.
function splitRow(line, n) {
  const parts = line.split(',')
  if (parts.length <= n) return parts
  return [...parts.slice(0, n - 1), parts.slice(n - 1).join(',')]
}

function num(v) {
  const n = Number(v)
  return Number.isFinite(n) ? n : null
}

// No forecast should display as 0% or 100%. Those are claims of certainty,
// and a model resting on a handful of polls two months out has no business
// making one. Pennsylvania at 99.96% rounds to 100% and reads as "this
// cannot happen", which is both wrong and the kind of number people
// screenshot. The stored value is untouched; only the display is clamped.
export const DISPLAY_FLOOR = 0.01
export const DISPLAY_CEIL = 0.99

export function forDisplay(p) {
  if (p === null || p === undefined) return p
  return Math.min(Math.max(p, DISPLAY_FLOOR), DISPLAY_CEIL)
}

// Venue strings carry a '-backfill' suffix for rows pulled from a venue's
// own history rather than observed live. Split them so the two can be told
// apart: backfilled rows are the venue's aggregation, not a request we made
// and timestamped, and they arrive daily where live rows arrive four times
// a day.
function splitVenue(venue) {
  const raw = venue || ''
  const backfill = raw.endsWith('-backfill')
  return { venue: backfill ? raw.slice(0, -9) : raw, backfill }
}

// Latest LIVE row per race per venue. Backfilled rows are deliberately
// excluded from "current": they stop at yesterday, and a stale backfill
// point would otherwise outrank a fresh observation on sort order alone.
function latestMarkets(rows) {
  const byRace = new Map()
  for (const row of rows) {
    if (row.note) continue        // failed fetches carry no price
    const prob = num(row.prob)
    if (prob === null) continue
    const { venue, backfill } = splitVenue(row.venue)
    if (backfill) continue

    if (!byRace.has(row.race_id)) byRace.set(row.race_id, {})
    const race = byRace.get(row.race_id)
    const prev = race[venue]
    if (!prev || row.fetched_at > prev.fetched_at) {
      race[venue] = {
        fetched_at: row.fetched_at,
        prob,
        volume: num(row.volume) ?? 0,
        days_out: num(row.days_out),
      }
    }
  }
  return byRace
}

// Full time series per race per venue, live and backfilled together, since
// for a chart the distinction does not change what the line means.
export function marketSeries(rows) {
  const byRace = new Map()
  for (const row of rows) {
    if (row.note) continue
    const prob = num(row.prob)
    const days = num(row.days_out)
    if (prob === null || days === null) continue
    const { venue } = splitVenue(row.venue)

    if (!byRace.has(row.race_id)) byRace.set(row.race_id, {})
    const race = byRace.get(row.race_id)
    if (!race[venue]) race[venue] = []
    race[venue].push({ days_out: days, prob })
  }

  for (const race of byRace.values()) {
    for (const key of Object.keys(race)) {
      // One point per day, most recent reading wins, ordered from the
      // furthest horizon toward election day.
      const byDay = new Map()
      for (const p of race[key]) byDay.set(p.days_out, p)
      race[key] = [...byDay.values()].sort((a, b) => b.days_out - a.days_out)
    }
  }
  return byRace
}

export function pollSeries(rows) {
  const byRace = new Map()
  for (const row of rows) {
    const prob = num(row.prob)
    const days = num(row.days_out)
    if (prob === null || days === null) continue
    if (!byRace.has(row.race_id)) byRace.set(row.race_id, [])
    byRace.get(row.race_id).push({ days_out: days, prob })
  }
  for (const [k, v] of byRace) {
    byRace.set(k, v.sort((a, b) => b.days_out - a.days_out))
  }
  return byRace
}

// Latest row per race from the converted poll probabilities.
function latestPolls(rows) {
  const byRace = new Map()
  for (const row of rows) {
    const prob = num(row.prob)
    if (prob === null) continue
    const prev = byRace.get(row.race_id)
    if (!prev || row.computed_at > prev.computed_at) {
      byRace.set(row.race_id, {
        computed_at: row.computed_at,
        prob,
        margin: num(row.margin),
        sigma: num(row.sigma),
        n_polls: num(row.n_polls),
        effective_n: num(row.effective_n),
        n_partisan: num(row.n_partisan) ?? 0,
      })
    }
  }
  return byRace
}

export function combine(marketRows, pollRows, meta = {}, historyRows = []) {
  const markets = latestMarkets(marketRows)
  const polls = latestPolls(pollRows)
  const mSeries = marketSeries(marketRows)
  const pSeries = pollSeries(historyRows)

  const ids = new Set([...markets.keys(), ...polls.keys()])
  const out = []

  for (const race_id of ids) {
    // A race is shown only if it is still in the metadata. Removing a race
    // from races.json stops new collection but leaves every row already
    // recorded, and the page builds its list from the snapshot file, so a
    // dropped race carries on displaying from history. Nebraska kept
    // showing "Republican >99%" for days after being removed for exactly
    // the reason it was removed: an independent held 29.5% and the
    // two-party framing could not represent it.
    //
    // The rows stay in the file. They are valid observations and worth
    // keeping; they simply stop being published.
    if (Object.keys(meta).length && !meta[race_id]) continue

    const venues = markets.get(race_id) || {}
    // Polymarket is the reference venue: it covers every race, while Kalshi
    // covers most. Kalshi stands in where Polymarket is missing.
    const m = venues.polymarket || venues.kalshi
    const p = polls.get(race_id)
    if (!m) continue              // no market price means nothing to compare

    const volume = m.volume ?? 0
    const info = meta[race_id] || FALLBACK_META

    // Two venues quoting the same contract should agree. A wide gap is a
    // data-quality alarm before it is a market signal: it caught a New
    // Hampshire ticker that pointed at the primary rather than the general.
    const both = venues.polymarket && venues.kalshi
    const venueGap = both
      ? (venues.polymarket.prob - venues.kalshi.prob) * 100
      : null

    const series = mSeries.get(race_id) || {}
    series.poll = pSeries.get(race_id) || []

    // Who each source favours. Both probabilities are P(Democrat wins), so
    // a source favours the Republican whenever it sits below 0.5.
    const marketFavours = m.prob >= 0.5 ? 'dem' : 'rep'
    const pollFavours = p ? (p.prob >= 0.5 ? 'dem' : 'rep') : null

    out.push({
      race_id,
      label: info.label,
      dem: info.dem,
      rep: info.rep,
      demShort: info.dem_short,
      repShort: info.rep_short,
      kind: info.kind,
      marketFavours,
      pollFavours,
      // The headline case: the two sources name different winners. Rarer
      // than a numeric gap and far more interesting, so it is computed
      // here rather than left for the component to infer.
      splitCall: pollFavours !== null && marketFavours !== pollFavours,
      // The gap is derived from the ROUNDED percentages, not the raw
      // probabilities. Rounding after subtracting produces a figure that
      // disagrees with the numbers printed above it: 53.5 and 46.9 display
      // as 54 and 47 but their raw difference rounds to 7 in one direction
      // and 6 in the other depending on the values. Subtracting what is
      // shown keeps the arithmetic on screen self-consistent.
      polymarket: venues.polymarket ? venues.polymarket.prob : null,
      kalshi: venues.kalshi ? venues.kalshi.prob : null,
      venueGap,
      venueDisagree: venueGap !== null && Math.abs(venueGap) > 5,
      series,
      market: m.prob,
      poll: p ? p.prob : null,
      gap: p ? Math.round(m.prob * 100) - Math.round(p.prob * 100) : null,
      margin: p ? p.margin : null,
      sigma: p ? p.sigma : null,
      n_polls: p ? p.n_polls : null,
      effective_n: p ? p.effective_n : null,
      n_partisan: p ? p.n_partisan : 0,
      days_out: m.days_out,
      volume,
      thinMarket: volume > 0 && volume < THIN_VOLUME,
      thinPolls: p ? p.effective_n < THIN_EFFECTIVE_N : false,
    })
  }

  // Sources naming different winners first, then biggest numeric gap.
  // A race where both agree is the least interesting row on the page.
  // Races with no poll data sort last rather than being dropped.
  return out.sort((a, b) => {
    if (a.splitCall !== b.splitCall) return a.splitCall ? -1 : 1
    if (a.gap === null && b.gap === null) {
      return Math.abs(0.5 - a.market) - Math.abs(0.5 - b.market)
    }
    if (a.gap === null) return 1
    if (b.gap === null) return -1
    return Math.abs(b.gap) - Math.abs(a.gap)
  })
}
