"""
Generate the social preview image shown when the site is shared.

    python3 make_og_image.py            # -> public/og.png
    python3 make_og_image.py --check    # report what it would draw

Needs Pillow:  pip install pillow --break-system-packages

WHY GENERATE RATHER THAN SHIP A STATIC ONE
------------------------------------------
The card is the entire pitch in a feed: most people decide from the unfurl
and never reach the page. A static image saying "prediction markets vs
polls" is a description. One saying "markets and polls disagree about who
wins 3 races" is a reason to click, and it can only say that if it is built
from current data.

Regenerated on every poll run, so the card ages with the site rather than
becoming a claim that stopped being true in September.

SIZE
1200x630 is the standard OG ratio. Platforms crop the edges unpredictably,
so nothing meaningful goes within about 60px of any border.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE.parent / "data"
# Written to a tracked directory, not public/. public/ is regenerated on
# every build and gitignored, so a card generated by the workflow would
# never reach the deployed site. copy-data.mjs copies it across at build
# time like the CSVs.
OUT = HERE.parent / "assets" / "og.png"

W, H = 1200, 630
PAD = 72

INK = (20, 22, 26)
INK_SOFT = (74, 79, 88)
INK_FAINT = (135, 141, 151)
PAPER = (250, 249, 247)
RULE = (226, 223, 217)
MARKET = (15, 110, 110)
POLL = (179, 113, 26)
FLAG = (154, 52, 18)


def load():
    """Latest market and poll probability per race, plus labels."""
    markets, polls, meta = {}, {}, {}

    snap = DATA / "snapshots.csv"
    if snap.exists():
        with snap.open(newline="", encoding="utf-8") as fh:
            for r in csv.DictReader(fh):
                if r.get("note") or "backfill" in (r.get("venue") or ""):
                    continue
                try:
                    prob = float(r["prob"])
                except (KeyError, TypeError, ValueError):
                    continue
                prev = markets.get(r["race_id"])
                if not prev or r["fetched_at"] > prev[1]:
                    markets[r["race_id"]] = (prob, r["fetched_at"])

    prob_file = DATA / "poll_probabilities.csv"
    if prob_file.exists():
        with prob_file.open(newline="", encoding="utf-8") as fh:
            for r in csv.DictReader(fh):
                try:
                    prob = float(r["prob"])
                except (KeyError, TypeError, ValueError):
                    continue
                prev = polls.get(r["race_id"])
                if not prev or r["computed_at"] > prev[1]:
                    polls[r["race_id"]] = (prob, r["computed_at"])

    meta_file = DATA / "race_meta.json"
    if meta_file.exists():
        meta = json.loads(meta_file.read_text())

    return markets, polls, meta


def splits(markets, polls, meta):
    """Races where the two sources name different winners, most extreme
    disagreement first."""
    out = []
    for race_id, (m, _) in markets.items():
        p = polls.get(race_id)
        if not p:
            continue
        p = p[0]
        if (m >= 0.5) == (p >= 0.5):
            continue
        info = meta.get(race_id, {})
        out.append({
            "race_id": race_id,
            "label": info.get("label") or race_id,
            "kind": info.get("kind", "senate"),
            "market_name": (info.get("dem_short") if m >= 0.5
                            else info.get("rep_short")) or "?",
            "poll_name": (info.get("dem_short") if p >= 0.5
                          else info.get("rep_short")) or "?",
            "gap": abs(round(m * 100) - round(p * 100)),
        })
    return sorted(out, key=lambda r: -r["gap"])


def font(size, bold=False):
    """Best available system face, falling back to Pillow's bitmap font."""
    from PIL import ImageFont
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold
        else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf" if bold
        else "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    ]
    for path in candidates:
        try:
            return ImageFont.truetype(path, size)
        except OSError:
            continue
    return ImageFont.load_default()


def draw_card(markets, polls, meta):
    from PIL import Image, ImageDraw

    img = Image.new("RGB", (W, H), PAPER)
    d = ImageDraw.Draw(img)

    disagreements = splits(markets, polls, meta)
    n_races = len(markets)
    y = PAD

    d.text((PAD, y), "ODDSVSPOLLS.COM", font=font(20), fill=INK_FAINT)
    y += 52

    # The headline is the finding, not the description. A card that says
    # what a site is gets read; one that says what it found gets clicked.
    if disagreements:
        n = len(disagreements)
        headline = (f"Markets and polls disagree\non who wins {n} "
                    f"{'race' if n == 1 else 'races'}")
    else:
        headline = "Where the markets and\nthe polls disagree"

    d.multiline_text((PAD, y), headline, font=font(62, bold=True),
                     fill=INK, spacing=16)
    y += 165

    d.text((PAD, y),
           f"{n_races} Senate and governor races, updated daily",
           font=font(26), fill=INK_SOFT)
    y += 62

    d.line([(PAD, y), (W - PAD, y)], fill=RULE, width=2)
    y += 34

    for race in disagreements[:3]:
        d.rectangle([PAD, y + 4, PAD + 4, y + 34], fill=FLAG)

        label = race["label"]
        if race["kind"] == "governor":
            label += " governor"
        d.text((PAD + 20, y), label, font=font(30, bold=True), fill=INK)

        detail = (f"market: {race['market_name']}   "
                  f"polls: {race['poll_name']}")
        d.text((PAD + 20, y + 40), detail, font=font(22), fill=INK_SOFT)

        gap = f"{race['gap']} pts"
        box = d.textbbox((0, 0), gap, font=font(30, bold=True))
        d.text((W - PAD - (box[2] - box[0]), y + 4), gap,
               font=font(30, bold=True), fill=FLAG)

        y += 82

    if not disagreements:
        d.text((PAD, y),
               "Every race: what the market says, what the polling implies,\n"
               "and the gap between them.",
               font=font(26), fill=INK_SOFT, spacing=12)

    stamp = datetime.now(timezone.utc).strftime("%d %B %Y")
    d.text((PAD, H - PAD - 20), stamp, font=font(20), fill=INK_FAINT)

    key = "Polymarket + Kalshi   |   VoteHub polling (CC BY 4.0)"
    box = d.textbbox((0, 0), key, font=font(20))
    d.text((W - PAD - (box[2] - box[0]), H - PAD - 20), key,
           font=font(20), fill=INK_FAINT)

    return img, disagreements, n_races


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    try:
        import PIL  # noqa: F401
    except ImportError:
        print("needs pillow: pip install pillow --break-system-packages",
              file=sys.stderr)
        return 1

    markets, polls, meta = load()
    if not markets:
        print("no market data; run ingest_markets.py first", file=sys.stderr)
        return 1

    img, disagreements, n_races = draw_card(markets, polls, meta)

    print(f"{n_races} races, {len(disagreements)} disagreements")
    for r in disagreements[:5]:
        print(f"  {r['label']:<18} market {r['market_name']:<12} "
              f"polls {r['poll_name']:<12} {r['gap']} pts")

    if args.check:
        print("\ncheck only, nothing written")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    img.save(OUT, "PNG", optimize=True)
    print(f"\nwrote {OUT.relative_to(HERE.parent)} "
          f"({OUT.stat().st_size / 1000:.0f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
